In [ ]:
'''
Quelle que soit la nature des données, elles peuvent être généralement considérées comme des tableaux de nombres. 
Par exemple, une image est un tableau à 2 dimensions contenant l'intensité  d'un pixel. 
Il est fondamental de pouvoir manipuler efficacement ces tableaux. 
En python, on utilise pour cela Numpy (Numerical Python) qui fournit une interface pour stocker 
et effectuer des opérations sur les données de manière efficace, même sur les tableaux de large taille. 

Dans cet exerice, vous devrez compléter les commentaires XXXXXXXX

'''

In [1]:
# Commençons par importer Numpy.
import numpy as np

In [ ]:
# Les tableaux Numpy ne peuvent contenir des éléments  d'UN SEUL  type. 
# Le type est  déduit au moment de la création du tableau, et a un impact sur les opérations 
# qui y seront appliquées. On peut aussi spécifier le type manuellement. 

# COMMENTAIRE : On crée un vecteur d'entiers
np.array([1, 4, 2, 5, 3])



# COMMENTAIRE : On crée un vecteur de flottants
np.array([3.14, 4, 2, 3])



In [ ]:
# COMMENTAIRE : On crée un vecteur dont on force le type à flottants
np.array([1, 2, 3, 4], dtype='float32')

In [5]:
# Contrairement aux listes Python, les tableaux Numpy peuvent être explicitement multi-dimensionnels. 
# COMMENTAIRE : On crée une liste de dimension 3*3 qui la remplie avec i, i+1, i+2 (d'où le range)
np.array([range(i, i + 3) for i in [2, 4, 6]])



array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
# COMMENTAIRE : On crée un liste remplie de 10 0 de type int
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# COMMENTAIRE : On crée une liste de flottants (ici 1) de dimension 3*5
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# COMMENTAIRE : On crée une liste de 3*5 remplie de 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
# COMMENTAIRE : On crée une liste qui va jusqu'à 20 de 2 en 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# COMMENTAIRE : On crée une liste qui de 0 à 1 et qui découpe cet intervalle en 5 
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
# COMMENTAIRE : Crée une liste de 3*3 remplie avec des flottants aléatoires entre 0 et 1
np.random.random((3, 3))

array([[0.40164012, 0.05464914, 0.72309045],
       [0.51885326, 0.56319868, 0.42639051],
       [0.2423031 , 0.72776263, 0.37620403]])

In [12]:
# COMMENTAIRE : Crée une liste de 3*3 avec des 1 dans les diagonales et des zéros partout ailleurs (matrice identité)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# COMMENTAIRE : Crée un tableau de classe numpy de 6 entiers aléatoires en 0 et 10 auquel on peut demander des paramètres particuliers
# comme sa dimension, son type ou sa taille
np.random.seed(0)
x1 = np.random.randint(10, size=6)  
print(x1)
print("nombre de dimensions de x1: ", x1.ndim)
print("forme de x1: ", x1.shape)
print("taille de x1: ", x1.size)
print("type de x1: ", x1.dtype)

[5 0 3 3 7 9]
nombre de dimensions de x1:  1
forme de x1:  (6,)
taille de x1:  6
type de x1:  int32


In [14]:
# COMMENTAIRE : Crée une liste de 3*3 de classe numpy remplie avec des flottants entre 0 et 1 auquel on peut demander certains 
# paramètres
x1 = np.random.random((3, 3))
print(x1)
print("nombre de dimensions de x1: ", x1.ndim)
print("forme de x1: ", x1.shape)
print("taille de x1: ", x1.size)
print("type de x1: ", x1.dtype)


[[0.6235637  0.38438171 0.29753461]
 [0.05671298 0.27265629 0.47766512]
 [0.81216873 0.47997717 0.3927848 ]]
nombre de dimensions de x1:  2
forme de x1:  (3, 3)
taille de x1:  9
type de x1:  float64


In [15]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)  # Tableau de dimension 1
print(x1)
# COMMENTAIRE :  Crée un tableau de 6 entiers entre 0 et 10 auquel on peut demander l'élément à une case d'indice donné
print(x1[0])

[5 0 3 3 7 9]
5


In [16]:
# COMMENTAIRE : Ce tableau permet de le parcourir même avec des indices négatifs évitant les effet de bords
print(x1[-1])

9


In [17]:
x2 = np.random.randint(10, size=(3, 4))  # Tableau de dimension 2
# COMMENTAIRE : Crée un tableau de dimension 3*4. On peut récupérer une valeur en ayant l'indice de la matrice
print(x2)
print(x2[0,1])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
5


In [18]:
# COMMENTAIRE : Permet de changer un valeur du tableau en donnant l'indice de la valeur à modifier en String mais 
# le constructeur doit le transformer en int par la suite car il faut que le String donné corresponde à un int pour
# ne pas avoir d'erreur
x1[1] = "1000"
print(x1)

# # COMMENTAIRE : Fonctionne mais transforme automatiquement les flottants en entiers
x1[1] = 3.14
print(x1)

[   5 1000    3    3    7    9]
[5 3 3 3 7 9]


In [20]:
#Accéder à plusieurs éléments

# De la même façon que nous pouvons indexer des éléments grâce à  [], nous pouvons accéder 
# à un ensemble d'éléments en combinant  []  et  :. 
# La syntaxe suit une règle simple :  x[début:fin:pas].
# Le début peut être omis si on veut commencer au début de la liste (c'est à dire si début = 0). 
# La fin peut être omise si on veut aller jusqu'au bout de la liste (c'est à dire fin = -1 ou fin = len(liste) ). 
# Le pas, ainsi que le dernier  :, peuvent être omis si le pas est de 1 (-1 si la fin est inférieure au début). 

print(x1)  

# COMMENTAIRE : Affiche le tableau de l'indice 5 
print(x1[:5])  

# COMMENTAIRE : XXXXXXXXXXXXXXX
print(x1[5:])  

# COMMENTAIRE : v
print(x1[::2])   

# COMMENTAIRE : XXXXXXXXXXXXXXX
x1[::-1]

[5 3 3 3 7 9]
[5 3 3]
[9]
[5 3 7]


array([9, 7, 3, 3, 3, 5])

In [ ]:
# On peut accéder de la même façon aux éléments d'un tableau multi-dimensionnel. 
# Par exemple, on a souvent besoin d'accéder à une ligne ou une colonne d'une matrice.

print(x2)
# COMMENTAIRE : XXXXXXXXXXXXXXX
x2[0,:] 

In [ ]:
#COMMENTAIRE : XXXXXXXXXXXXXXX
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

In [ ]:
# COMMENTAIRE : XXXXXXXXXXXXXXX
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

np.vstack([x, grid])

In [ ]:
# L'implémentation de référence de Python, encore appelée CPython, est très flexible, 
# mais cette flexibilité l'empêche d'utiliser toutes les optimisations possibles. 
# Par exemple, observez le temps d'exécution de ce morceau de code

def calcul_inverse(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        

# Calcul sur un petit tableau
values = np.random.randint(1, 10, size=5)
print(calcul_inverse(values))
%timeit calcul_inverse(values)

# Calcul sur un grand tableau avec la fonction
tableau_large = np.random.randint(1, 100, size=1000000)
%timeit calcul_inverse(tableau_large)
# Calcul sur un grand tableau avec la version optimisé
%timeit (1.0 / tableau_large)

# COMMENTAIRE : XXXXXXXXXXXXXXX

In [ ]:
# COMMENTAIRE : # XXXXXXXXXXXXXXX
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # Division avec arronid

In [ ]:
# COMMENTAIRE : # XXXXXXXXXXXXXXX
x = [-2, -1, 1, 2]
print("La valeur absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print("Logarithme: ", np.log(np.abs(x)))

In [ ]:
# COMMENTAIRE : # XXXXXXXXXXXXXXX
x = np.random.rand(3,3)
print(x)
x > 0.5

In [ ]:
# COMMENTAIRE : XXXXXXXXXXXXXXX
np.where(x > 0.5)

In [ ]:
# Très souvent, face à de larges quantités de données, la première chose à faire est de calculer 
# des statistiques sur nos données, comme la moyenne ou l'écart type. 
# Numpy a des fonctions pour calculer ces données sur ses tableaux.

# COMMENTAIRE :  XXXXXXXXXXXXXXX
%timeit sum(tableau_large)
%timeit np.sum(tableau_large)

In [ ]:
M = np.random.random((3, 4))
print(M)
# Notez la syntax variable.fonction au lieu de # np.fonction(variable). 
# Les deux sont possibles si la variable est un tableau Numpy.

# COMMENTAIRE : XXXXXXXXXXXXXXX
print("La somme de tous les éléments de M: ", M.sum())
print("Les sommes des colonnes de M: ", M.sum(axis=0))

In [ ]:
#Parmi les nombreuses fonctions disponibles, notons :
#  np.std  pour calculer l'écart type
#  np.argmin  pour trouver l'index de l'élément minimum
#  np.percentile  pour calculer des statistiques sur les éléments.

In [ ]:
# Le broadcasting désigne un ensemble de règles pour appliquer une opération qui normalement ne s'applique 
# que sur une seule valeur à l'ensemble des membres d'un tableau Numpy. 

# COMMENTAIRE : XXXXXXXXXXXXXXX
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b


In [ ]:
# COMMENTAIRE : XXXXXXXXXXXXXXX
a + 5

In [ ]:
# COMMENTAIRE : XXXXXXXXXXXXXXX
M = np.ones((3, 3))
print("M vaut: \n", M)
print("M+a vaut: \n", M+a)

In [ ]:
a = np.arange(3)
# COMMENTAIRE : XXXXXXXXXXXXXXX
b = np.arange(3)[:, np.newaxis]

In [ ]:
print(a)
print(b)
a+b